#!/bin/bash

if [[ "$(uname)" == "Darwin" ]]; then
    readlink() { greadlink "$@"; }
fi

cur="$(dirname "$(readlink -f "$0")")"
mkdir -p "$cur/build"
pushd "$cur/build"
rm -rf ../bundle

params=()

case "$(uname -s)" in
    Darwin) params+=(-DQt5_DIR=$(brew --prefix qt5)/lib/cmake/Qt5);;
    MINGW*) params+=(-G "MSYS Makefiles");;
esac

params+=(../src)

export MACOS_DEPLOYMENT_TARGET=10.12
cmake "${params[@]}" && cmake --build . && cmake --build . --target install
